//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4200
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOLConfig {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOLConfig.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap add_property_button_Image {
			get {
				object obj = ResourceManager.GetObject("add_property_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bu_spChange_Image {
			get {
				object obj = ResourceManager.GetObject("bu_spChange.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap delete_property_button_Image {
			get {
				object obj = ResourceManager.GetObject("delete_property_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap edit_property_button_Image {
			get {
				object obj = ResourceManager.GetObject("edit_property_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mysql_test_button_Image {
			get {
				object obj = ResourceManager.GetObject("mysql_test_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap save_config_button_Image {
			get {
				object obj = ResourceManager.GetObject("save_config_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap set_default_values_button_Image {
			get {
				object obj = ResourceManager.GetObject("set_default_values_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap xml_database_path_button_Image {
			get {
				object obj = ResourceManager.GetObject("xml_database_path_button.Image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
