name: Net4.8 Tests on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        build_target: [Debug, Release]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Build Dependencies
        run: |
          sudo apt install -y mono-devel nuget
          nuget install NUnit.Console -Version 3.12.0 -OutputDirectory test -ExcludeVersion
      - name: Build
        run: |
          CONFIGURATION=${{ matrix.build_target }} nuget restore
          MONO_IOMAP=case msbuild /p:Configuration=${{ matrix.build_target }} "Dawn of Light.sln"
      - name: Test
        run: |
          LANG=en_US.CP1252 mono ./test/NUnit.ConsoleRunner/tools/nunit3-console.exe ./build/Tests/${{ matrix.build_target }}/lib/Tests.dll --where "namespace =~ 'DOL.UnitTests' and category!='Explicit'"
          LANG=en_US.CP1252 mono ./test/NUnit.ConsoleRunner/tools/nunit3-console.exe ./build/Tests/${{ matrix.build_target }}/lib/Tests.dll --where "namespace =~ 'DOL.Integration' and category!='Explicit'"
