name: Test Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test_netcore_linux:
    name: NetCore Tests on Linux
    strategy:
      matrix:
        build_target: [Debug]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: |
          dotnet build -c ${{ matrix.build_target }} "NetCore/Tests/Tests.csproj" --verbosity normal
      - name: Test
        run: |
          dotnet test ./NetCore/build/Tests/${{ matrix.build_target }}/lib/Tests.dll -v n --filter "DOL.UnitTests&TestCategory!=Explicit"
          dotnet test ./NetCore/build/Tests/${{ matrix.build_target }}/lib/Tests.dll -v n --filter "DOL.Integration&TestCategory!=Explicit"

  test_netcore_windows:
    name: NetCore Tests on Windows
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        build_target: [Debug]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: |
          dotnet build -c ${{ matrix.build_target }} "NetCore/DOLdotnet.sln" --verbosity normal
      - name: Test
        run: |
          dotnet test .\NetCore\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.UnitTests&TestCategory!=Explicit"
          dotnet test .\NetCore\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.Integration&TestCategory!=Explicit"

  test_netframework_linux:
    name: Net 4.8 Tests on Linux
    strategy:
      matrix:
        build_target: [Debug, Release]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c ${{ matrix.build_target }} "Tests/Tests.csproj" --verbosity normal
      - name: Test
        run: |
          dotnet test ./build/Tests/${{ matrix.build_target }}/lib/Tests.dll -v n --filter "DOL.UnitTests&TestCategory!=Explicit"
          dotnet test ./build/Tests/${{ matrix.build_target }}/lib/Tests.dll -v n --filter "DOL.Integration&TestCategory!=Explicit"

  test_netframework_windows:
    name: Net 4.8 Tests on windows
    strategy:
      matrix:
        build_target: [Debug, Release]
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c ${{ matrix.build_target }} "Tests\Tests.csproj" --verbosity normal
      - name: Test
        run: |
          dotnet test .\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.UnitTests&TestCategory!=Explicit"
          dotnet test .\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.Integration&TestCategory!=Explicit"
