name: .Net5 Tests on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        build_target: [Debug]
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build -c ${{ matrix.build_target }} "Net5/DOLdotnet.sln"
      - name: Test
        run: |
          dotnet test .\Net5\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.UnitTests"
          dotnet test .\Net5\build\Tests\${{ matrix.build_target }}\lib\Tests.dll -v n --filter "DOL.Integration"
